void sample1gbox1init(int i,void *Tmp) ;
int  sample1splbutton1callback(int butno,int i,void *Tmp) ;
void  sample1splbutton1init(DIL *B,void *pt) ;
int  sample1button1callback(int butno,int i,void *Tmp) ;
void  sample1button1init(DIN *B,void *pt) ;
int sample1init(void *Tmp) ;
int sample1cleanup(void *Tmp) ;
int sample1CallBack(void *Tmp,void *tmp) ;
int sample1ResizeCallBack(void *Tmp) ;
int sample1WaitCallBack(void *Tmp) ;
