int  ButnTypebutton1callback(int butno,int i,void *Tmp) ;
void  ButnTypebutton1init(DIN *B,void *pt) ;
int  ButnTypebutton2callback(int butno,int i,void *Tmp) ;
void  ButnTypebutton2init(DIN *B,void *pt) ;
int  ButnTypebutton3callback(int butno,int i,void *Tmp) ;
void  ButnTypebutton3init(DIN *B,void *pt) ;
int  ButnTypebutton4callback(int butno,int i,void *Tmp) ;
void  ButnTypebutton4init(DIN *B,void *pt) ;
int  ButnTypebutton5callback(int butno,int i,void *Tmp) ;
void  ButnTypebutton5init(DIN *B,void *pt) ;
int  ButnTypebutton6callback(int butno,int i,void *Tmp) ;
void  ButnTypebutton6init(DIN *B,void *pt) ;
int  ButnTypebutton7callback(int butno,int i,void *Tmp) ;
void  ButnTypebutton7init(DIN *B,void *pt) ;
int  ButnTypebutton8callback(int butno,int i,void *Tmp) ;
void  ButnTypebutton8init(DIN *B,void *pt) ;
int  ButnTypebutton9callback(int butno,int i,void *Tmp) ;
void  ButnTypebutton9init(DIN *B,void *pt) ;
int  ButnTypebutton10callback(int butno,int i,void *Tmp) ;
void  ButnTypebutton10init(DIN *B,void *pt) ;
int  ButnTypebutton11callback(int butno,int i,void *Tmp) ;
void  ButnTypebutton11init(DIN *B,void *pt) ;
int  ButnTypesplbutton1callback(int butno,int i,void *Tmp) ;
void  ButnTypesplbutton1init(DIL *B,void *pt) ;
int ButnTypeinit(void *Tmp) ;
int ButnTypecleanup(void *Tmp) ;
int ModifyButnType(void *Tmp,int GrpId) ;
int ButnTypeCallBack(void *Tmp,void *tmp) ;
int ButnTypeResizeCallBack(void *Tmp) ;
int ButnTypeWaitCallBack(void *Tmp) ;
