int demodemoSplbuttoncallback(int butno,int i,void *Tmp) ;
void  demodemoSplbuttoninit (DIL *B,void *pt) ;
int demodemoButton0callback(int butno,int i,void *Tmp) ;
void  demodemoButton0init (DIN *B,void *pt) ;
int demodemoButton2callback(int butno,int i,void *Tmp) ;
void  demodemoButton2init (DIN *B,void *pt) ;
int demodemoButton1callback(int butno,int i,void *Tmp) ;
void  demodemoButton1init (DIN *B,void *pt) ;
int demodemoButton3callback(int butno,int i,void *Tmp) ;
void  demodemoButton3init (DIN *B,void *pt) ;
int demodemoButton4callback(int butno,int i,void *Tmp) ;
void  demodemoButton4init (DIN *B,void *pt) ;
int demodemoFoldercallback(int butno,int i,void *Tmp) ;
void  demodemoFolderinit (DIN *B,void *pt) ;
int demodemoButton6callback(int butno,int i,void *Tmp) ;
void  demodemoButton6init (DIN *B,void *pt) ;
int demodemoButton7callback(int butno,int i,void *Tmp) ;
void  demodemoButton7init (DIN *B,void *pt) ;
int demodemoButton8callback(int butno,int i,void *Tmp) ;
void  demodemoButton8init (DIN *B,void *pt) ;
int demodemoButton9callback(int butno,int i,void *Tmp) ;
void  demodemoButton9init (DIN *B,void *pt) ;
int demodemoButton10callback(int butno,int i,void *Tmp) ;
void  demodemoButton10init (DIN *B,void *pt) ;
int demodemoPulldowncallback(int item,int i,void *Tmp) ;
int demodemoTextboxcallback(int cellno,int i,void *Tmp) ;
int demodemoTablecallback(int cellno,int i,void *Tmp) ;
int demodemoDslidecallback(int  val,int i,void *Tmp) ;
int demodemoFslidecallback(double val,int i,void *Tmp) ;
void demodemoGboxinit (int i,void *Tmp) ;
int demodemoEboxcallback(int item,int i,void *Tmp) ;
void * demodemoEboxinit (DIE *E,void *pt) ;
void * demodemoMsgscrollinit (DIS *S,void *pt) ;
int demodemoHBslidecallback(int val,int i,void *Tmp) ;
int demodemoXboxcallback(int item,int i,void *Tmp) ;
void  demodemoXboxinit (DIX *X,void *pt) ;
int demodemoRadiocallback(int item,int i,void *Tmp) ;
void  demodemoRadioinit (DIRA *R,void *pt) ;
int demodempChboxcallback(int item,int i,void *Tmp) ;
void  demodempChboxinit (DICH *C,void *pt) ;
int demodemoYboxcallback(int item,int i,void *Tmp) ;
void  demodemoYboxinit (DIY *Y,void *pt) ;
int demodemoVbarcallback(double val,int i,void *Tmp) ;
int demodemoHbarcallback(double val,int i,void *Tmp) ;
int demodemoButton5callback(int butno,int i,void *Tmp) ;
void  demodemoButton5init (DIN *B,void *pt) ;
int demoinit(void *Tmp) ;
int democleanup(void *Tmp) ;
void *Rundemo(void *,void *) ;
int MakedemoGroup(DIALOG *,void *) ;
void * demoAction(void *,void *) ;
int demoSetup(void *Tmp,void *args) ;
int Modifydemo(void *Tmp,int GrpId) ;
int demoCallBack(void *Tmp,void *tmp) ;
int demoResizeCallBack(void *Tmp) ;
int demoWaitCallBack(void *Tmp) ;
