int  EditThumbnailsbutton1callback(int butno,int i,void *Tmp) ;
void  EditThumbnailsbutton1init(DIN *B,void *pt) ;
int  EditThumbnailssplbutton1callback(int butno,int i,void *Tmp) ;
void  EditThumbnailssplbutton1init(DIL *B,void *pt) ;
int  EditThumbnailsbrowser1callback(int item,int i,void *Tmp) ;
void  EditThumbnailsbrowser1init(DIY *Y,void *pt) ;
int EditThumbnailsinit(void *Tmp) ;
int EditThumbnailscleanup(void *Tmp) ;
int ModifyEditThumbnails(void *Tmp,int GrpId) ;
int EditThumbnailsCallBack(void *Tmp,void *tmp) ;
int EditThumbnailsResizeCallBack(void *Tmp) ;
int EditThumbnailsWaitCallBack(void *Tmp) ;
