int  EditWidgetsbrowser1callback(int item,int i,void *Tmp) ;
void  EditWidgetsbrowser1init(DIY *Y,void *pt) ;
int  EditWidgetssplbutton1callback(int butno,int i,void *Tmp) ;
void  EditWidgetssplbutton1init(DIL *B,void *pt) ;
int EditWidgetsinit(void *Tmp) ;
int EditWidgetscleanup(void *Tmp) ;
int ModifyEditWidgets(void *Tmp,int GrpId) ;
int EditWidgetsCallBack(void *Tmp,void *tmp) ;
int EditWidgetsResizeCallBack(void *Tmp) ;
int EditWidgetsWaitCallBack(void *Tmp) ;
